### ISSUE TITLE
Allow/disallow additional properties option

### ISSUE THREAD

**Issue by amygdalama** [pipermerriam/flex#101]
With JSON Schema's [`additionalProperties`](http://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties), by default any additional properties are allowed. However, I'd like to enforce the opposite -- additional properties are disallowed unless `additionalProperties` is specified.

For implementation, I was thinking I could add an argument `allow_additional_properties` to [`validate`](https://github.com/pipermerriam/flex/blob/1f995dbdad577ad5264bd090ddddbdd08417d1e5/flex/core.py#L102). `allow_additional_properties` would default to `True`, preserving the current default behavior. Then I'd pass that option through to `construct_schema_validators` to where we check [if `additionalProperties` is `False`](https://github.com/pipermerriam/flex/blob/1f995dbdad577ad5264bd090ddddbdd08417d1e5/flex/validation/schema.py#L223), and modify that conditional to also disallow `additionalProperties` if `allow_additional_properties` is `False`. Seems like this would work for `validate`, but I'd also want to add the option to `validate_response`. I'll need to do some more digging to see how to do that, since it looks like it doesn't call `construct_schema_validators`, but maybe I'm wrong about that.

Does this feature interest you? What do you think about the suggested implementation? I'd be happy to take a stab at it.

**Comment by pipermerriam** [comment]
This library's validation rules need to conform to the swagger 2.0 schema so any functionality that is implemented needs to be done so in accordance with the schema.

A quick look at the swagger docs and corresponding json-schema documentation suggests that the current implementation is incorrect and that the behavior that you are requesting is what should be enforced when `additionalProperties == False`.

Human readable explanation of how to use the `additionalProperties` value can be found here.  http://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties

So, I would be more than happy to have you adjust the current implementation to handle `additionalProperties` correctly which I believe is the desired functionality.

**Comment by amygdalama** [comment]
Ah, yeah, I think the current implementation handles setting `additionalProperties: False` correctly. I'd like the option to have `additionalProperties` _default_ to `False` if not specified, which is the opposite of how json schema works.

Here's my use case, maybe this'll clear things up: I want `additionalProperties` to be `False` for every endpoint. Right now, this means I need to add `additionalProperties: False` everywhere in my spec, which is doable but mildly tedious. But then I don't have a great way to enforce that new endpoints added set `additionalProperties: False` (or to be sure that I set it everywhere). I could do some custom linting, etc, to enforce this, but I thought maybe using flex to default `additionalProperties` would be easier to implement, so I wanted to run it by you first.

**Comment by pipermerriam** [comment]
I'm not keen on implementing a feature specifically for this use case as it seems non-standard.  If you can demonstrate that this is something that a broad enough base of the flex user base would like then I'll open to re-opening this issue.
