### ISSUE TITLE
Response status code validation doesn't work

### ISSUE THREAD

**Issue by maroux** [pipermerriam/flex#108]
`validate_api_call` doesn't normalize the requests correctly - swagger responses objects keys are strings, not integers whereas flex expects them to be integers and thus isn't able to correctly validate.

I was able to get around this issue by setting `response.status_code` as a string value.

**Comment by pipermerriam** [comment]
This should be pretty simple to fix by adding the appropriate type casting somewhere around [here](https://github.com/pipermerriam/flex/blob/master/flex/http.py#L189)

**Comment by maroux** [comment]
Yep. Agreed. Just wanted to make sure it's a real but before sending in a
PR.

**Comment by pipermerriam** [comment]
This should be available on pypi as `5.4.0`

**Comment by maroux** [comment]
Thanks!

**Comment by simon-weber** [comment]
The yaml parsing should probably be adjusted too, since it seems idiomatic to use `200:` and not `"200":`. Swagger-ui uses this for their example at http://editor.swagger.io/#.

But, after the change, specs like that will cause an error, eg:
```
Request status code was not found in the known response codes.  Got `200`: Expected one of: `[200]`
```

**Comment by maroux** [comment]
@simon-weber not sure what you mean by that - are you talking about `flex.core.load` for loading a YAML file? If so, that should load the dictionary with `string` (rather than `int`) as per YAML spec. And `json.loads` will fail to load an invalid JSON (such as `{"1": 2}`).

**Comment by simon-weber** [comment]
> that should load the dictionary with string (rather than int) as per YAML spec

Huh. pyyaml/flex seem to parse it as an int for me, eg:
```shell
# go to http://editor.swagger.io/#, hit "file > download yaml", then:
$ python -c 'import flex; s = flex.load("swagger.yaml"); code = s["paths"]["/products"]["get"]["responses"].keys()[0]; print code, type(code)'
200 <type 'int'>
```

However, http://yaml-online-parser.appspot.com/ will parse the same yaml to a string.

**Comment by maroux** [comment]
@simon-weber ah you're totally right. Odd that yaml parses that as int. In any case, this looks like a bug in swagger-editor since `responses.keys` are supposed to be strings as per Swagger v2.0 spec.

**Comment by simon-weber** [comment]
Sounds good; I'll raise it with them.
