### ISSUE TITLE
Question: Flask/Werkzeug request validation

### ISSUE THREAD

**Issue by ivan-c** [pipermerriam/flex#110]
Has support for [Flask](https://flask.readthedocs.org/en/latest/api/#flask.Request)/[Werkzeug](http://werkzeug.pocoo.org/docs/0.11/wrappers/) request/response classes ever been considered?

It looks trivial to add a new [REQUEST_NORMALIZER](https://github.com/pipermerriam/flex/blob/ed3d7ddbbb694002a58030561d43a223f8ac785c/flex/http.py#L151) but I thought I'd ask before getting over my head.

Thanks!

**Comment by pipermerriam** [comment]
By all means, I'd love to see this implemented.  Let me know if you need any help navigating the codebase.

**Comment by zenwalker** [comment]
@ivan-c 
Any progress on this issue? Looks like it needs me too.
