### ISSUE TITLE
Query Parameter Validation Error - Invalid data type

### ISSUE THREAD

**Issue by xuejiezhang** [pipermerriam/flex#112]
I'm using V5.4.0.
In swagger.json, the query parameter is defined as follows:
  "parameters": {
    "countQuery": {
      "default": 10,
      "description": "Get this number of objects from the collection. Valid values are 1 to 100, default 10.",
      "in": "query",
      "minimum": 1,
      "name": "count",
      "type": "integer"
    },

when accessing the following URL: http://***/subscriptions?count=1, got the following error:

 'parameters':
        - 'query':
            - 'count':
                - 'type': 
                  - \"Got value `'1'` of type `string`.  Value must be of type(s): `('integer',)`\"",

Thanks,
Jeff

**Comment by xuejiezhang** [comment]
link to  https://github.com/pipermerriam/flex/issues/20#issuecomment-216394746

**Comment by pipermerriam** [comment]
Going to use #112 as the authoritative issue for this bug.
