### ISSUE TITLE
Content-type header encoding handling

### ISSUE THREAD

**Issue by YuChem** [pipermerriam/flex#117]
Error on valid according to [RFC-2045 #5.1](https://www.ietf.org/rfc/rfc2045.txt) header `Content-Type: application/json; charset=utf-8` . The  error message:

```
NotImplementedError: No content negotiation for this content type
```

The code in question is `http.py`

``` python
        if self.content is EMPTY:
            return self.content
        elif self.content_type == 'application/json':
            if isinstance(self.content, six.binary_type):
                return json.loads(six.text_type(self.content, encoding='utf-8'))
            else:
                return json.loads(self.content)
        raise NotImplementedError("No content negotiation for this content type")
```

**Comment by ahartoto** [comment]
@YuChem @pipermerriam, I think we can close this now

**Comment by blag** [comment]
This should be fixed: https://github.com/pipermerriam/flex/blob/233f8149fb851a6255753bcec948cb6fefb2723b/flex/http.py#L101

Closing.
