### ISSUE TITLE
Validation for the $ref part of the schema under allOf is broken

### ISSUE THREAD

**Issue by haizaar** [pipermerriam/flex#146]
Validation on properties defines through $ref under allOff seems to work only once. Here is the full reproduction:

```
import requests
from flex.core import load, validate_api_request
import flex.exceptions

raw_schema = """
swagger: "2.0"
info:
  title: API
  description: API
  version: "1.0"
basePath: /api/v1
consumes:
  - application/json

paths:
  /users:
    post:
      summary: Create a new user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserPost"
      responses:
        "201":
          description: OK

definitions:
  UserBase:
    type: object
    description: Base object for users
    properties:
      name:
        type: string
        maxLength: 100
    required: ["name"]

  UserPost:
    type: object
    description: An object to create a user
    allOf:
      - $ref: "#/definitions/UserBase"  # <---- This is the part of schema that gets ignored starting from the second invokcation.
      - properties:
          user_id:
            type: string
            description: ID of a user
            maxLength: 128
        required: ["user_id"]
"""


def validate(schema, request):
    try:
        validate_api_request(schema, raw_request=request)
    except flex.exceptions.ValidationError:
        pass
    else:
        raise Exception("False positive")

schema = load(raw_schema)
response = requests.post("http://example.com/api/v1/users", json={"user_id": "asdf"})
validate(schema, response.request)
print("First pass OK")
validate(schema, response.request)
```

Here the *first* call to `validate_api_request` properly raises `ValidationError` about missing `name` parameter. However the second call goes silent. If I reload the schema, it comes back to life, but its obviously not a way to go.

P.S. Thanks for the awesome lib.

**Comment by vasilyIvanov** [comment]
Seems like an issue is located inside this method:
```
def generate_allof_validator(allOf, context, **kwargs):
    context.setdefault('resolved_refs', [])
    unresolved_refs = []
    for ref in allOf:
        if isinstance(ref, dict) and '$ref' in ref:
            schema = ref['$ref']
            if schema not in context['resolved_refs']:
                unresolved_refs.append(ref) 
                context['resolved_refs'].append(schema)
        else:
            unresolved_refs.append(ref)

    return functools.partial(validate_allof_anyof, sub_schemas=unresolved_refs,
                             context=context, method=all)
```

Namely `unresolved_refs.append(ref)` is called only when `schema` not in `context['resolved_refs']`. That's why validation works correctly only first time.

If we move `unresolved_refs.append(ref)` out of `if` condition:
```
def generate_allof_validator_fixed(allOf, context, **kwargs):
    context.setdefault('resolved_refs', [])

    sub_schemas = []
    for ref in allOf:
        sub_schemas.append(ref)
        if isinstance(ref, dict) and '$ref' in ref:
            schema = ref['$ref']
            if schema not in context['resolved_refs']:
                context['resolved_refs'].append(schema)

    return functools.partial(validate_allof_anyof, sub_schemas=sub_schemas,
                             context=context, method=all)
```

Then we would face another problem: infinite recursion like `validate base object -> add polymorphism requirements -> validate sub object -> validate base object`. We can try breaking infinite recursion by calling `add_polymorphism_requirements` only once for each object. In order to do it we should tag polymorph objects somehow: wrap them into some special tagging object or add meta properties to the very object like `__reqs_added__` (it's much more dirty way).

So me personally solved this problem by simple monkey patching.

I don't dare making a PR about it since I can break something. Would be great to have some regression unit testing.

**Comment by haizaar** [comment]
Thanks for the detailed elaboration. I wonder why didn't anyone complained on this before - sounds like a very basic bug to me; so, again, I wonder why aren't maintainers alerted by it.

I understand regarding the PR, but can you please share your monkey patch at least? That would really help.

**Comment by pipermerriam** [comment]
Thank you for reporting this.  I've not got the bandwidth to fix this but I'll happily support the effort when someone is able to take it on.

**Comment by maroux** [comment]
Running into the same issue.

@trapsignal isn't discriminator only valid in `oneOf` and `anyOf` (per https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/). I'm not sure why `allOf` validator is affected by this? This solution (https://github.com/pipermerriam/flex/pull/183/files) seems reasonable to me..

**Comment by maroux** [comment]
On second thought, it's better to have a solution that doesn't modify schema dict so you can load schema once and re-use for multiple API call validations..
