### ISSUE TITLE
Best way to specify we only want to validate the response?

### ISSUE THREAD

**Issue by harrisj** [pipermerriam/flex#149]
Things have been working great for 200 responses from my API, but I am interested in using flex to validate API responses for invalid inputs like when a query parameter is not within an enum. The issue I have right now is that the validator rejects the request as being malformed (which it is by design) before it verifies the response. I'd like to file a PR to allow me to just validate the response, but it seems like there are a few options I can explore:

1. Call `validate_response` directly, but this seems like I am violating the abstraction, and I would also need to normalize the response before I pass it in. But this would work now without any changes, I think
2. Refactor the `validate_api_call` method to call a `validate_api_response` method that is a wrapper around the `normalize_response` and `validate_response` methods that I could just call from methods where I want to validate the response.
3. Add a parameter like `only=` to `validate_api_call` that takes either `response` or `request` as arguments and uses that for calling the validation.

I was leaning towards the third option at first, but I realized that people might think they don't have to pass in a request object when `only=response` but we still need that request object to know the HTTP method we are validating the response for. So I am kinda leaning towards the second option since it makes that more explicit. What do you think?

**Comment by ahartoto** [comment]
I vote for option 2
