### ISSUE TITLE
Extend formats to allow values to be modified (rather than just validated)

### ISSUE THREAD

**Issue by petedmarsh** [pipermerriam/flex#162]
I would like to be able to define a custom format that's  able to convert a value to something else, rather than just checking it matches a format. I think it'd be nice to be able to do this with flex as it has the type/format information available to it, and it's already has to walk through the input to validate it - it avoids passing along the type information to some other piece of code of code and going through the input data again.

This does move away from pure swagger validation, but I think it would be useful - the most common case I can think of is converting date/times in JSON from strings to `datetime.datetime`s, and I'm sure there are more.

I'd be happy to implement this - I don't think it would be too difficult, but I wondered if you felt it would be appropriate for this project and, if so, what you thought the API would look like? My initial thoughts were something like this:

```python
#...
from flex.formats import register
@register('title-case', 'string')
def title_case_format_validator(value, coerce=False):
     if coerce:
         return value.title()
     if not value == value.title():
         raise ValidationError("Must be title cased")

#...
validate(schema, request, coerce_formats=True)
```

However, I'm sure there's room for improvement.

**Comment by pipermerriam** [comment]
I don't believe Flex is the appropriate home for this type of feature as it's a validation tool (as opposed to something meant to process data).  If this becomes part of the core spec I'm happy to reconsider.
