### ISSUE TITLE
Provide richer error objects

### ISSUE THREAD

**Issue by petedmarsh** [pipermerriam/flex#165]
When a request is validated against a schema any and all of the errors that are generated are bundled into a single `ValidationError` as strings, this works well for human-readability as the errors look something like this:

```
ValidationError: 'method':
    - 'parameters':
        - 'request_body':
            - '$ref':
                - 'additionalProperties':
                    - u"When `additionalProperties` is False, no unspecified properties are allowed.  The following unspecified properties were found:\n\t`set([u'this'])`"
                - 'required':
                    - 'name':
                        - u'This value is required'
```

However, it's difficult/messy to extract further details from the errors programatically - getting the set of additional properties for example.

It would be great if the errors were richer objects so they're easier to program against.

**Comment by pipermerriam** [comment]
I like this idea and it should be quite easy to implement.

**Comment by pipermerriam** [comment]
This is actually already the case, there is just no documentation for it.  See https://github.com/pipermerriam/flex/blob/master/flex/exceptions.py#L63

If you'd like to write some quick documentation for it this can be exposed as a public API.
