### ISSUE TITLE
How mature/complete is flex ?

### ISSUE THREAD

**Issue by sys-git** [pipermerriam/flex#197]
# Just to clarify:

`It is currently at a very early stage in development and thus is likely to have plenty of bugs.`

setup.py says `pre-alpha`

but...

version at `6.x`

**Comment by pipermerriam** [comment]
Flex is relatively mature and complete as far as the swagger 2.0 spec is concerned.  This library is however not actively developed or maintained, other than by community contributions.  Those lines could be removed from docs.

**Comment by blag** [comment]
Answered and resolved in #198 and 1b00814e186b9ef8bfd4405d1431196f8427c63f.
