### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by ivlevdenis** [pipermerriam/flex#203]
Error when install in py3.7 env.
Need update req in setup.py, "PyYAML>=3.11,<4" to "PyYAML>=3.11"

**Comment by pipermerriam** [comment]
Open ended version requirements allow for upstream breaking changes (from major version bumps) to break things.  Instead, we need to upgrade to `PyYAML>=4,<5` (or whatever version is required to support python3.7.  We may need to do conditional version installs to retain support for older pythons but we can cross that bridge if we get there.

**Comment by blag** [comment]
This should be fixed in the latest release (`v6.14.0`).
