### ISSUE TITLE
Typo in generated maximum validation messages

### ISSUE THREAD

**Issue by eugenedruy** [pipermerriam/flex#208]
validate_maximum in validation/common.py makes comparison_text  equal to either string
"less than"
or 
"less than or equal to"
Then comparison_text is inserted into a preformatted error message
"{0} must be {1} than {2}"
(see error_messages.py  :  MINIMUM_AND_MAXIMUM_MESSAGES)
resulting to a message like
"<value name> must be less than or equal to _**than**_ <value>"
Please remove 'than' from the format string for "invalid" entry for MINIMUM_AND_MAXIMUM_MESSAGES

**Comment by blag** [comment]
This sounds like an easy fix. Can you turn this into a PR?

**Comment by manojatsolace** [comment]
As a flex user, Solace would love to get this fix for our PubSub+ broker. Thanks in advance!

**Comment by blag** [comment]
@manojatsolace PRs welcome.

**Comment by connormoss** [comment]
Would liked to see this fixed as well! Thanks
