### ISSUE TITLE
Update documentation for validate_api_call

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#45]
The validate_api_call method was updated but the documentation was not updated.

In this [commit](https://github.com/pipermerriam/flex/commit/6dd40bf9ce451b2e48565432acb0a32e79c0afc0#diff-f3a867d094642f074d48613d6330c28f) the validate_api_call was changed:
```ssh
-def validate_api_call(schema, request, response):
+def validate_api_call(schema, raw_request, raw_response):
```
So the documentation should be updated

**Comment by pipermerriam** [comment]
Fixed in #45
