### ISSUE TITLE
Validate maxLenght of an string

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#51]
It would be nice if flex validate the maxLenght of a string. For example:

```ssh
properties:
   mystring:
        type: string
        maxLenght: 10
```

If *mystring* has more than 10 characters, flex raise an Error

**Comment by pipermerriam** [comment]
Can you provide a code example for this?

It looks like you have `maxLength` mispelled.  Note the `t` and `h` are transposed in your example schema.  I'm not sure if this is copy/pasted from your code.

**Comment by nicolastrres** [comment]
Oh I see, I was misspelling :/ 
I thought this feature was not implemented yet. 
Sorry for that, and thanks for the quick feedback :)
