### ISSUE TITLE
Request path did not match any of the known api paths

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#52]
Hi, I am struggling with this new problem, I am using this example:
```ssh
/v1/pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          description: The id of the pet to retrieve
          type: string
      responses:
        200:
          description: Expected response to a valid request
          schema:
            $ref: Pets
        default:
          description: unexpected error
          schema:
            $ref: Error
```
And when I do this:
```ssh
import requests
from flex.core import load, validate_api_call
schema = load("schema.yaml")
response = requests.get('/v1/pets/dog')
validate_api_call(schema, raw_request=response.request, raw_response=response)
```
For some reason I am getting this error:
```ssh
flex.exceptions.ValidationError: 'request':
    - 'path':
        - 'Request path did not match any of the known api paths.'
```

Is there something specific I should do in the schema to solve this?

**Comment by pipermerriam** [comment]
Can you drop into a debugger (pdb) statement at this place in the code.

https://github.com/pipermerriam/flex/blob/master/flex/validation/common.py#L459

That `LookupError` is the source of the validation error.  The `LookupError` comes from https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L125.  What I'm curious about is whether the exception is coming from line 128 "No paths found" or line 130 "Multiple Paths Found".

Either way, If you can also give me a dump of the `paths` variable defined at https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L116 that will help.

**Comment by pipermerriam** [comment]
Also, I *think* that if you pass your schema through `flex.core.validate` you're going to get some errors around your parameter definitions.  Specifically, the `required` field of a parameter is required if the parameter is in the `path`.


https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-7

**Comment by pipermerriam** [comment]
Also, what version of flex are you using?

**Comment by nicolastrres** [comment]
Hi @pipermerriam thanks again for the quick response, I am going to respond your questions:
- **the exception is coming from line 128 "No paths found" or line 130 "Multiple Paths Found".?** The exception is coming from line 128 "No paths found"

- My paths are: 
```ssh 
{'/v1/pets/{petId}': re.compile('^/v1/pets/\\{petId\\}$'), 
'/v1/pets/': re.compile('^/v1/pets/$')}
```

-  **The required field of a parameter is required if the parameter is in the path.** . Yes, I solved that before, adding the required into the swagger.

- **What version of flex are you using?** I am using flex 3.0.0

**Comment by pipermerriam** [comment]
It *looks* like the regex for the `/v1/pets/{petId}` is being compiled without knowledge of the `petId` parameter.

Can you head back into the `match_path_to_api_path` function and get the values of both `global_parameters` and `(v or {}).get('parameters', []) for v in path_definitions.items()`

What I'm looking for is whether the `petId` parameter is present in either of those lists.

**Comment by nicolastrres** [comment]
The global_parameters are {}
And the path_definitions it seems it has all the swagger schema, including the petId parameter:
```ssh
'/v1/pets/{petId}': {'get': 
  {'summary': 'Info for a specific pet', 'operationId': 'showPetById', 'tags': ['pets'],
  'responses': {200: {'description': 'Expected response to a valid request', 
  'schema': {'$ref': 'Pets'}}}, 'parameters': [{'required': True, 'in': 'path', 
  'description': 'The id of the pet to retrieve', 'name': 'petId', 'type': 'string}
```

**Comment by nicolastrres** [comment]
I think I found the problem, in this line:
https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L119

This expression: (v or {}).get('parameters', []) is always returning []

Do you know why this can be happening?

**Comment by nicolastrres** [comment]
I am going to try to explain what I found:
Our v variable [here](https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L119) it something like this:
```ssh
v = {'get': 
{'parameters': [{'required': True, 'name': 'petId', 'description': 'The id of the pet to retrieve', 'in': 'path', 'type': 'string'}],
 'summary': 'Info for a specific pet', 
'operationId': 'showPetById', 
'responses': {200: {'description': 'Expected response to a valid request', 'schema': {'$ref': 'Pets'}}}, 
'tags': ['pets']}}
```
How you can see this (v or {}).get('parameters', []) is always returning [] because v.get('parameters') doesn't exist. What I mean is that if we do v.get('get') we will get this:
```ssh
{'parameters': [{'required': True, 'name': 'petId', 'description': 'The id of the pet to retrieve', 'in': 'path', 'type': 'string'}], 
'summary': 'Info for a specific pet', 
'operationId': 'showPetById', 
'responses': {200: {'description': 'Expected response to a valid request', 'schema': {'$ref': 'Pets'}}}, 
'tags': ['pets']}
```
and if we do v.get('get').get('parameters'), we are going to get the parameters:
```ssh
[{'required': True, 'type': 'string', 'description': 'The id of the pet to retrieve', 'in': 'path', 'name': 'petId'}]
```

**Comment by pipermerriam** [comment]
Ah!

https://github.com/pipermerriam/flex/pull/55

Wasn't looking at the parameters defined at the operation level.  Once this passes, I'll get a 3.1.0 released sometime today.

**Comment by nicolastrres** [comment]
Great!!! :D 
Thanks @pipermerriam!

**Comment by pipermerriam** [comment]
Really glad to have you using flex and reporting these issues.  Lots of these bugs are present due to my use cases only exposing bugs related to how I use swagger.  Glad to have a broader audience.

**Comment by pipermerriam** [comment]
You should be able to get 3.1.0 off pypi

https://pypi.python.org/pypi/flex/3.1.0

**Comment by nicolastrres** [comment]
Awesome! Thanks again!
