### ISSUE TITLE
Multiple paths found - Request path did not match any of the known api paths

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#56]
Hi, I am facing new issues. Take a look at this: 
```ssh
/v1/pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          description: The id of the pet to retrieve
          type: string
      responses:
        200:
          description: Expected response to a valid request
          schema:
            $ref: Pets
/v1/pets/{petId}/name/{namePet}:
    get:
      description: get an pet with name
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          description: ID of the pet
          required: true
          type: string
        - name: namePet
          in: path
          description: name of the pet
          required: true
          type: string
      responses:
        200:
          description: response of the pet
          schema:
              $ref: Pets
```
The problem is that [this line](https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L145):
```ssh
 matches = [p for p, r in paths.items() if r.match(target_path)]
```
Returns more than one match:
```ssh
['/v1/pets/{petId}', '/v1/pets/{petId}/name/{namePet}']
```
And I am getting the error: Request path did not match any of the known api paths.
I think that is not the expected behaviour, right?

**Comment by pipermerriam** [comment]
> And I am getting the error: *Request path did not match any of the known api paths*.
I think that is not the expected behaviour, right?

Well, it's the designed behavior with a misleading error message.  I wrote that original code not sure how to deal with multiple matches so I decided, an error is better than guessing until I could figure out a better approach.

As for the multiple matches, it has to do with how I construct the regex patterns that match against the paths.  I think I have an idea for how to deal with this issue, but it'll probably be tomorrow before I can get to anything.

**Comment by pipermerriam** [comment]
Ok, fix going in via #57

I'm still a bit unhappy with this section of the code so I'm going to create a new issue attempting to describe the future issues that should be cleaned up.  Thanks for finding this.  I'll get a new release out as soon as tests are passing in my branch.

**Comment by pipermerriam** [comment]
3.2.0 up on pypi

https://pypi.python.org/pypi/flex/3.2.0

**Comment by nicolastrres** [comment]
Great! Thanks @pipermerriam :)
