### ISSUE TITLE
No paths found for /pets/dog.us

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#61]
Hello, I am facing a new issue with the url validation. 
My url is something like this: http://localhost/pets/dog.us?type=2&age=1
My swagger is something like this:
```ssh
basePath: /localhost
paths:
  /pets/dog.us?type=2&age=1
    get:
      summary: Get dogs of type 2 and age 1
      responses:
        200:
          schema:
            $ref: Type2Age1
```
I am getting this error:
```ssh
libs.flex.exceptions.ValidationError: 'request':
    - 'path':
        - 'No paths found for /pets/dog.us'
```
I took a look to [paths](https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L137) : 
```ssh
{'/pets/dog.us?type=2&age=1': re.compile('^/pets/dog\\.us?type=2&age=1$')}
```
And the [matching_api_paths](https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L147):
```ssh
[]
```

What do you think about the problem? Am I defining the path in 'swagger' wrongly? or do you think that is a flex issue?

**Comment by pipermerriam** [comment]
I don't think that your swagger schema is valid

```yaml
basePath: /localhost
paths:
  /pets/dog.us?type=2&age=1
    get:
      summary: Get dogs of type 2 and age 1
      responses:
        200:
          schema:
            $ref: Type2Age1
```

Specifically the path.  I think you would have to define the query parameters as follows.

```yaml
basePath: /localhost
paths:
  /pets/dog.us
    get:
        parameters:
            - name: type
              in: "query"
              type: integer
            - name: age
              in: "query"
              type: integer
      summary: Get dogs of type 2 and age 1
      responses:
        200:
          schema:
            $ref: Type2Age1
```

Seeing as swagger defines a way to specify query parameters it seems odd to include them in the actual path string.  That said, I don't see any place where swagger explicitly forbids including them in the path string so I am *open* to a pull request that expands how the path regex is generated to correctly  match paths like this, though I'm not sure it's the appropriate thing to do...

Thoughts?

**Comment by nicolastrres** [comment]
You are totally right, I should use the query parameters. My problem is because the '/pets/dog.us?type=2&age=1' and '/pets/dog.us?type=3&age=1' return a total structure, so I wanted to put the paths in the path string. But I think that I should change my software and use the query parameters.
