### ISSUE TITLE
Flex doesn't find referenced definitions

### ISSUE THREAD

**Issue by EBichel** [pipermerriam/flex#66]
I am encountering a reference bug with flex (3.5.0).. It doesn't find referenced types in "#/definitions".. A sample:

```json
 {
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0",
    "title" : "Sample Rest API"
  },
  "basePath" : "/",
  "schemes" : [ "http" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/status" : {
      "post" : {
        "parameters" : [ {
						"in":"body",
						"name": "token",
						"schema" : {"$ref" : "#/definitions/TokenObj"}
          }
         ],
        "responses" : {
          "200" : {
            "description" : "retrieves the status"
          }
        }
      }
    }
  },
  "definitions" : {
    "TokenObj" : {
      "required" : [ "magic", "timestamp" ],
      "properties" : {
        "magic" : {
          "type" : "string"
        },
        "timestamp" : {
          "type" : "string"
        }
      },
      "type" : "object"
    }
  }
}
```

I receive the following output:
```
ValidationError: 'paths':
    - u'/status':
        - 'post':
            - 'parameters':
                - 'schema':
                    - '$ref':
                        - u'Unknown definition reference `#/definitions/TokenObj`'
```

This is only the simplest sample I could produce. References to #/parameters are working, but anything referencing items in #/definitions seems to be failing.

**Comment by nicolastrres** [comment]
Have you tried with this? :
```ssh
"schema" : {"$ref" : "TokenObj"}
```
I had the same problem.

**Comment by EBichel** [comment]
This solves the problem of loading it with flex, but causes errors in the "official" swagger editor and other swagger-parser related things. I am not sure, if this is a reliable and "portable" solution of the problem. I also created a second version with a problem of referencen to `#/parameters` which also fails

```json
{
	"swagger": "2.0",
	"info": {
		"title": 	"Sample Rest API",
		"version":	"1.0"
	},
	"basePath": "/",
	"schemes": 	["http"],
	"consumes": ["application/json"],
	"produces": ["application/json"],
	"paths" : {
		"/status" : {
			"post" : {
				"parameters" : [{
						"name" : "token",
						"in" : "body",
						"schema": {
							"$ref": "#/parameters/tokenParameter"
						}
					}
				],
				"responses" : {
					"200" : {
						"description" : "retrieves the status"
					}
				}
			}
		}
	},
	"parameters": {
		"tokenParameter": {
			"in": "body",
			"name": "token",
			"schema": { "$ref": "#/definitions/TokenObj" }
		}	
	},
	"definitions": {
		"TokenObj" : {
			"type": "object",
			"required": ["magic", "timestamp"],
			"properties": {
					"magic" : {
						"type": "string"
					},
					"timestamp": {
						"type": "string"
					}
			}
		}
	}
}
```
The suggested solution by you isn't applicable in this case.
As a further problem, flex insists that as a parameter a simple reference is not enough. There have to be at least a `name` and `in`. However, the swagger spec schema specifies this case of only a schema reference like this: 
```json
		"parameters" : [{
										"$ref": "#/parameters/tokenParameter"
			}
		]
```

My examplse are valid in the editor. I know that the editor does have its flaws, because sometimes it isn't parsing this strictly enough. However, in my opinion it seems to be a problem with flex, because I also want to use my API specification in other tools.

**Comment by pipermerriam** [comment]
@EBichel Thanks for reporting this.  I'm accepting this as a bug.  Looks like I overlooked the notes about how references should be formatted as [`JSON Pointers`](http://tools.ietf.org/html/rfc6901).

@nicolastrres I'm going to maintain backwards incompatibility for a few versions.  `flex` doesn't currently have a policy on deprecation or backwards incompatibility so I'd like to figure out a nice balance between still being able to iterate quickly and not introducing sudden breaking changes.  Do you have any thoughts on how long you guys might need to get your schema's converted over to using `JSON Pointer` style references?

**Comment by pipermerriam** [comment]
References for myself

- http://tools.ietf.org/html/rfc6901
- http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-02

**Comment by pipermerriam** [comment]
BTW, @EBichel it *may* be 1-2 weeks before I can get to this.  If you feel comfortable putting in a PR for this it's welcome.

A good starting point in the code is the `LazyReference` object  https://github.com/pipermerriam/flex/blob/master/flex/validation/schema.py#L169

**Comment by nicolastrres** [comment]
@pipermerriam When this is fix, I am going to move our code to the new version. So you shouldn't worry about the backward compatibility.

**Comment by EBichel** [comment]
Thanks for accepting my report as a bug.
I did some research and the problem is that definitions are in the `context['definitions']` dictionary, but without any hint for its reference value.. In the validation phase it is not found. The error is thrown in https://github.com/pipermerriam/flex/blob/master/flex/loading/schema/paths/path_item/operation/responses/single/schema/ref.py#L25 . If there would be an item under definitions with the path `#/definitions/item/` it should not be a problem.
Maybe a possible solution is to save the items as `context['definitions']['#/definitions/item']`... But this seems to be redundant for me.. I am not experienced with Python, so I am not sure if I can make a good fix...

**Comment by pipermerriam** [comment]
Started digging into this this morning.

Note to self: http://json-schema.org/latest/json-schema-core.html#anchor27

**Comment by kvlahromei** [comment]
I'm not sure if this is related to exactly this bug, but flex 3.5.1 doesn't seem to work with the current official petstore example anymore:

    schema = flex.load("http://petstore.swagger.io/v2/swagger.json")

> ValidationError: 'definitions':
    - u'#/definitions/Tag':
        - u'The $ref `#/definitions/Tag` is referenced but never defined'
    - u'#/definitions/Category':
        - u'The $ref `#/definitions/Category` is referenced but never defined'

**Comment by pipermerriam** [comment]
Yes, this is the same issue.  Going to try and find some time for this
issue today.

**Comment by pipermerriam** [comment]
This is fixed and up on pypi on version `4.0.0`

https://pypi.python.org/pypi/flex/4.0.0

This version is backwards incompatible with the previous implementation which was fundamentally incorrect with respect to RFC6901 as well as the Swagger 2.0 spec.

**Comment by EBichel** [comment]
Thanks a lot for fixing this bug!

**Comment by pipermerriam** [comment]
Your welcome.  

And FYI, this fix only enables references to objects defined in the local schema.  Referencing other local or remote files is not yet supported.
