### ISSUE TITLE
AttributeError: 'int' object has no attribute 'get'

### ISSUE THREAD

**Issue by MattiSG** [pipermerriam/flex#68]
```
$ flex --source http://openfisca.sgmap.fr/api/1/swagger
Traceback (most recent call last):
…
  File "/usr/local/lib/python2.7/site-packages/flex/decorators.py", line 112, in inner
    kwargs[key] = obj.get(key, EMPTY)
AttributeError: 'int' object has no attribute 'get'
```

**Comment by pipermerriam** [comment]
Thanks for the big report.  I'll look into this today.

**Comment by pipermerriam** [comment]
Also.  What version are you using.

**Comment by MattiSG** [comment]
`3.5.0`, just installed it  ;)

Let me know if I can give any additional information!  :)

**Comment by pipermerriam** [comment]
You can get the fix for this in `3.5.1` which is up on pypi

https://pypi.python.org/pypi/flex/3.5.1

**Comment by MattiSG** [comment]
Wow, pretty impressive reaction time! Congratulations and thanks  :)

**Comment by pipermerriam** [comment]
Happy to have you using it.  Please let me know if you find anything else.
