### ISSUE TITLE
Validation incorrectly allows additional properties

### ISSUE THREAD

**Issue by gaaf** [pipermerriam/flex#82]
Validation allows additional properties if "additionalProperties" is set to False in the schema. Instead, the validator should raise an exception. The JSON Schema validation specification, [section 5.4.4.4](http://json-schema.org/latest/json-schema-validation.html#anchor68) contains the rules on how to handle "additionalProperties".

```python
from flex.core import validate
schema = {
  'type': 'object',
  'additionalProperties': False,
  'properties': {
    'name': {
      'type': 'string',
      'minLength': 3,
    },
  }
}
data = {
  'wrong': 10,
}
validate(schema, data)
```

**Comment by nicolastrres** [comment]
:+1: @pipermerriam I am facing the same problem when I try to use the validate_api_call

**Comment by pipermerriam** [comment]
Thanks for reporting this.

**Comment by pipermerriam** [comment]
@nicolastrres and @gaaf 

Sorry for the long turnaround on this.  #83 should fix this.  I'll try to get a release out early this week.

**Comment by pipermerriam** [comment]
You should be able to get `4.2.0` off of pypi
