### ISSUE TITLE
Improve the maxLength validation message

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#84]
Hi @pipermerriam I found something that seems an error
```yaml
amount:
    type: string
    maxLength: 2
```

But when I send an amount of 5 characters, I got the validation message:
```ssh
flex.exceptions.ValidationError: 'response':
    - 'body':
        - 'schema':
            - '$ref':
                - 'amount':
                    - 'maxLength':
                        - 'value must be no greater than 5 characters in length.'
```
The message should be something like `value must be no greater than 2 characters in length`
I am using the last version of flex.

**Comment by pipermerriam** [comment]
@nicolastrres you should be able to get [`4.2.1`](https://pypi.python.org/pypi/flex/4.2.1) of pypi
