### ISSUE TITLE
Flex is not validating correctly an url with query parameter

### ISSUE THREAD

**Issue by roselmamendes** [pipermerriam/flex#87]
We added a new url with query parameter on our project, and we would like check this using Flex.
But we noticed when url with query parameter is not specified into swagger file, Flex doesn't validate correctly. 
We have created a test to that before make any adding to swagger file, and Flex act as test is fine.
We assumed hope that Flex would show a error if this is trying call a url with query parameter, if this one is not specified in the swagger file.

**Comment by pipermerriam** [comment]
Can you please include a sample of the schema and code that raises this error?

**Comment by pipermerriam** [comment]
Hrm, I think I actually mis-understood your issue.

Is it accurate to say that you expect an error to be shown if an un-specified query parameter is included in a request?

I am not sure if swagger provides a mechanism to disallow unspecified query parameters.

**Comment by roselmamendes** [comment]
Yes, that is what I meant.

**Comment by pipermerriam** [comment]
This is something that you'll need to bring up with the official swagger spec.

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameterObject

If they are willing to add a way to specify that only explicitly declared query parameters are allowed, I'll happily add support for it in `flex`
