### ISSUE TITLE
Add validation of the request body parameters

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/flex#9]
Response validation should validate the body parameters.

**Comment by nicolastrres** [comment]
Hi, @pipermerriam do you have any news on this?

**Comment by pipermerriam** [comment]
I don't but I'd like to get it in soon. Unfortunately, I have a bunch of stuff stacked up right now that is higher priority.  Probably 2 weeks before I can dive back into this for anything other than bug fixes.

**if** someone were to want to implement this themselves, I would happily give guidance and feedback on it.  Feel free to poke me again in a week or so about this.  I do care about getting this in soon and pestering is a good way to get me to work on this.
