### ISSUE TITLE
'contact' validation

### ISSUE THREAD

**Issue by giacbrd** [pipermerriam/flex#92]
The 'contact' field should be an object, according to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#contact-object .
When I try to load a schema with the contacts defined as in the above documentation, I receive an exception. 
(Is this the file to fix? https://github.com/pipermerriam/flex/blob/master/flex/loading/schema/info.py)

**Comment by pipermerriam** [comment]
That is the correct file to fix.

Would you be willing to submit a PR changing that schema?

**Comment by snordhausen** [comment]
It seems this was already fixed with 481f69684a393b722822b4cc79172ffc0e816401 and can be closed.
