### ISSUE TITLE
Please rename the command line tool

### ISSUE THREAD

**Issue by cdeil** [pipermerriam/flex#93]
Could you please rename the command line tool to avoid the conflict with this tool?
https://en.wikipedia.org/wiki/Flex_(lexical_analyser_generator)

I see that this name conflict was already discussed in
https://github.com/pipermerriam/flex/issues/18#issuecomment-63671100
but didn't result in a change?

This came up here: https://github.com/sherpa/sherpa/issues/146

**Comment by pipermerriam** [comment]
Fixing via https://github.com/pipermerriam/flex/pull/94 thanks for bringing this back to my attention.  It had long slipped from my radar.

**Comment by cdeil** [comment]
@pipermerriam - Thank you!
